- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: java setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: install python dependencies
  ansible.builtin.pip:
    name:
      - cryptography
      - PyMySQL
    executable: pip3.9

- name: import schema
  community.mysql.mysql_db:
    state: import
    name: shipping
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    target: /app/db/schema.sql

- name: import app-user
  community.mysql.mysql_query:
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    query: "{{ lookup('file', '/app/db/app-user.sql') }}"

- name: import master data
  community.mysql.mysql_query:
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    query: "{{ lookup('file', '/app/db/master-data.sql') }}"

- name: start and enable shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes